apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: sabata/nodejs-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: MYSQL_HOST
          value: db-service
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: Admin123!
        - name: MYSQL_DATABASE
          value: test
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
  - port: 4000
    targetPort: 4000
  type: LoadBalancer  
